### ISSUE TITLE
Update for 0.7.7

### ISSUE THREAD

**Issue by imevro** [paolodm/angular-selectize#1]
Selectize.js is now on version 0.7.7 and demo (and directive) is not working.

**Comment by jejernig** [comment]
shameless bump!

**Comment by betz** [comment]
Replace

$(element).selectize(scope.$eval(attrs.selectize));

with

element.selectize(scope.$eval(attrs.selectize));

**Comment by imevro** [comment]
Forked and updated https://github.com/theaqua/ng-selectize
Thanks, @betz!
